/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fhbzarxmiftlubqznpcl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoYnphcnhtaWZ0bHVicXpucGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MDc4NjgsImV4cCI6MjA3MDE4Mzg2OH0.fy0Ma0-KevxEEc0QWFuu4mimttNaqQUH2zBH9tTENNE"
export const makeBaseUrl = `https://${projectId}.supabase.co/functions/v1/make-server-e08b724b`